### ISSUE TITLE
Proxy support with SSL

### ISSUE THREAD

**Issue by katowulf** [square/SocketRocket#265]
For us, #114 is still relevant. Although, in our case, we only support encrypted traffic, so we would need this to work with HTTPS traffic. Firebase is using SocketRocket for our iOS SDK and currently, customers are affected by lack of proxy support. This is fairly common with corporate policy in the education sector. 

If SocketRocket could allow proxies with SSL it would allow us to push out a new release to resolve this issue.

**Comment by peterfdo** [comment]
@mikelikespie , Agree with @katowulf on #114. Almost all of our education users in Australia and New Zealand, and many other international users, are *blocked completely* from using our app running Firebase. We have *no workaround* to address the issue. Our app is designed for use in schools, and given that it's summer here in the US, the majority of our traffic is from those southern hemisphere countries right now. We understand that you have other priorities and appreciate any help we can get, but until then, our active user base is dwindling because of this seasonal traffic.

**Comment by angrykilobyte** [comment]
Also agree with @katowulf on #114. Our application runs in a corporate environment, and many customers would like to have their users' devices go through their proxy.

**Comment by shofmn** [comment]
Agree with the posts above. I'm working for a worldwide software company (top 5) and we also experience this issue that we can't open a websocket secure connection within the corporate network due to missing proxy support.
Would be great to have this enabled in SocketRocket - then this would definitely be the library of our choice!

**Comment by dfed** [comment]
Reopened the original. Thanks for letting us know! Closing this.
