### ISSUE TITLE
Last frame of a connection not always processed with iOS 9

### ISSUE THREAD

**Issue by kommen** [square/SocketRocket#268]
We're seeing an issue which started to appear with iOS 9 betas. It occurs, when the server sends data to the SocketRocket client and then immediately closes the connection.

In my testing, there's about a 50% chance, that the last frame sent from the server is not passed to the delegate via `webSocket:didReceiveMessage`.

I did some digging, and found the following:
* when `NSStreamEventEndEncountered` is handled, the last frame the server sent is present in the `_readBuffer`
* when [`_pumpScanner`][0] is called, it [exits early][1] because `_consumers` is empty, apparently causing the frame not to be read from the `_readBuffer`

[0]: https://github.com/square/SocketRocket/blob/master/SocketRocket/SRWebSocket.m#L1422
[1]: https://github.com/square/SocketRocket/blob/master/SocketRocket/SRWebSocket.m#L1164

Some notes:
* I can only reproduce the problem with `SRFastLog` disabled (i.e `SR_ENABLE_LOG` undefined)
* Interestingly I can only reproduce this with a server on the internet, and not if the server is on the local network. Simulating network conditions with the Network Link Conditioner also doesn't make it reproducible with the local server

Unfortunately I don't have enough insight into SRWebSocket yet for why that could be the case. Any pointers?

**Comment by joenoon** [comment]
@kommen are you still seeing this?  I'm having similar trouble with the server closing the connection and SocketRocket hitting this NSStreamEventEndEncountered before receiving the last thing the server sent.  I'm seeing this in React Native which uses basically a copy of SocketRocket, but I think the code in question is the same.

I've tracked it down to inside this else block:

https://github.com/square/SocketRocket/blob/master/SocketRocket/SRWebSocket.m#L1438

If I wrap everything in that else block in a `dispatch_async(_workQueue, ^{...})` then my issue goes away, and I can see with logging that NSStreamEventEndEncountered is encountered, but then the final message is successfully received before the connection is disposed client-side.  My guess is dispatching this out allows the current execution loop to finish checking for data.  It seems racy regardless.

I'm mostly confused why it doesn't seem like others are having this issue, and the code block that does this has been there since 2012.

**Comment by joenoon** [comment]
I've create a PR for this if anyone could take a look: https://github.com/square/SocketRocket/pull/294

**Comment by kommen** [comment]
@joenoon yeah, we're still hitting that, but we had an easy work around for our app so investigating this had low priority for us.

I'll give your PR a try and see if this helps in our case as well.

For why others don't seem to having this issue: I was wondering that too. Seems to happen too often for us that no one else is running into that.

**Comment by mikelehen** [comment]
It'd be really great to get this fixed.  It actually completely breaks Firebase when the issue comes up because our workflow involves the server basically sending:

1. Go connect to this other host instead.
2. <closes socket>

And when SocketRocket doesn't deliver #1, the Firebase Client keeps reconnecting to the wrong server.  Demand for Firebase and React-Native has been high, so I'd love to see this addressed! :-)

**Comment by kommen** [comment]
I can confirm #294 fixed this issue for us. Thank you @joenoon!
